# Generated by Django 3.1 on 2022-03-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cartitem_variations'),
        ('store', '0007_auto_20220325_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
