# Generated by Django 3.1 on 2022-03-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product_gallery', 'verbose_name_plural': 'product_gallery'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
