# Generated by Django 3.1 on 2022-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220402_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='default_product1.png', upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='default_product2.png', upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='default_product3.png', upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='default_product4.png', upload_to='photos/products'),
        ),
    ]
