# Generated by Django 3.1 on 2022-04-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220413_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='file',
        ),
    ]
