# Generated by Django 3.1 on 2022-04-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220413_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='file',
            new_name='image',
        ),
    ]
