# Generated by Django 3.1 on 2022-04-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220414_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='image',
            new_name='images',
        ),
    ]
