# Generated by Django 3.1 on 2022-04-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_nett_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nett_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
